INSERT INTO "AvatarItem" (
    "key",
    "slot",
    "name",
    "description",
    "requiredLevel",
    "rarity",
    "layerOrder",
    "colorPrimary",
    "colorSecondary",
    "isActive",
    "updatedAt"
) VALUES
('character-smiley-pink', 'character', 'Smiley-Entdecker mit rosa Haaren', 'Vollständige Smiley-Figur mit rosa Haaren.', 2, 'COMMON', 10, '#d8589d', '#1f5eb8', true, CURRENT_TIMESTAMP),
('character-smiley-blue', 'character', 'Smiley-Entdecker mit blauen Haaren', 'Vollständige Smiley-Figur mit blauen Haaren.', 2, 'COMMON', 10, '#2877bd', '#1f5eb8', true, CURRENT_TIMESTAMP),
('character-smiley-brown', 'character', 'Smiley-Entdecker mit braunen Haaren', 'Vollständige Smiley-Figur mit braunen Haaren.', 2, 'COMMON', 10, '#68422d', '#1f5eb8', true, CURRENT_TIMESTAMP),
('character-smiley-blonde', 'character', 'Smiley-Entdecker mit blonden Haaren', 'Vollständige Smiley-Figur mit blonden Haaren.', 2, 'COMMON', 10, '#e7bd59', '#1f5eb8', true, CURRENT_TIMESTAMP),
('character-smiley-black', 'character', 'Smiley-Entdecker mit schwarzen Haaren', 'Vollständige Smiley-Figur mit schwarzen Haaren.', 2, 'COMMON', 10, '#202531', '#1f5eb8', true, CURRENT_TIMESTAMP),
('character-explorer-red', 'character', 'Wald-Entdeckerin mit roten Haaren', 'Vollständige Entdecker-Figur mit roten Haaren.', 4, 'UNCOMMON', 10, '#b64b32', '#4d6533', true, CURRENT_TIMESTAMP),
('character-explorer-pink', 'character', 'Wald-Entdeckerin mit rosa Haaren', 'Vollständige Entdecker-Figur mit rosa Haaren.', 4, 'UNCOMMON', 10, '#d8589d', '#4d6533', true, CURRENT_TIMESTAMP),
('character-explorer-blue', 'character', 'Wald-Entdeckerin mit blauen Haaren', 'Vollständige Entdecker-Figur mit blauen Haaren.', 4, 'UNCOMMON', 10, '#2877bd', '#4d6533', true, CURRENT_TIMESTAMP),
('character-explorer-brown', 'character', 'Wald-Entdeckerin mit braunen Haaren', 'Vollständige Entdecker-Figur mit braunen Haaren.', 4, 'UNCOMMON', 10, '#68422d', '#4d6533', true, CURRENT_TIMESTAMP),
('character-explorer-black', 'character', 'Wald-Entdeckerin mit schwarzen Haaren', 'Vollständige Entdecker-Figur mit schwarzen Haaren.', 4, 'UNCOMMON', 10, '#202531', '#4d6533', true, CURRENT_TIMESTAMP),
('character-star-red', 'character', 'Sternen-Heldin mit roten Haaren', 'Vollständige Sternen-Figur mit roten Haaren.', 3, 'UNCOMMON', 10, '#b64b32', '#1857a7', true, CURRENT_TIMESTAMP),
('character-star-blue', 'character', 'Sternen-Heldin mit blauen Haaren', 'Vollständige Sternen-Figur mit blauen Haaren.', 3, 'UNCOMMON', 10, '#2877bd', '#1857a7', true, CURRENT_TIMESTAMP),
('character-star-brown', 'character', 'Sternen-Heldin mit braunen Haaren', 'Vollständige Sternen-Figur mit braunen Haaren.', 3, 'UNCOMMON', 10, '#68422d', '#1857a7', true, CURRENT_TIMESTAMP),
('character-star-blonde', 'character', 'Sternen-Heldin mit blonden Haaren', 'Vollständige Sternen-Figur mit blonden Haaren.', 3, 'UNCOMMON', 10, '#e7bd59', '#1857a7', true, CURRENT_TIMESTAMP),
('character-star-black', 'character', 'Sternen-Heldin mit schwarzen Haaren', 'Vollständige Sternen-Figur mit schwarzen Haaren.', 3, 'UNCOMMON', 10, '#202531', '#1857a7', true, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO UPDATE SET
    "slot" = EXCLUDED."slot",
    "name" = EXCLUDED."name",
    "description" = EXCLUDED."description",
    "requiredLevel" = EXCLUDED."requiredLevel",
    "rarity" = EXCLUDED."rarity",
    "layerOrder" = EXCLUDED."layerOrder",
    "colorPrimary" = EXCLUDED."colorPrimary",
    "colorSecondary" = EXCLUDED."colorSecondary",
    "isActive" = true,
    "updatedAt" = CURRENT_TIMESTAMP;
