INSERT INTO "AvatarItem" ("key", "slot", "name", "description", "requiredLevel", "rarity", "layerOrder", "colorPrimary", "colorSecondary", "updatedAt") VALUES
('hair-pixel-short', 'hair', 'Pixel-Schopf', 'Kurzer 8-Bit-Abenteuerlook.', 1, 'COMMON', 30, '#5b3826', '#2f1d14', CURRENT_TIMESTAMP),
('hair-pixel-long', 'hair', 'Pixel-Langhaar', 'Laengerer Pixel-Haarschnitt.', 1, 'COMMON', 30, '#7a4729', '#4e2b18', CURRENT_TIMESTAMP),
('hair-pixel-wild', 'hair', 'Wilder Pixel-Look', 'Freche, zackige Haare.', 2, 'COMMON', 30, '#2f2a28', '#171514', CURRENT_TIMESTAMP),
('hair-pixel-blue', 'hair', 'Blaue Pixelstraehne', 'Seltene blaue Abenteuerstraehne.', 5, 'RARE', 30, '#3c79d8', '#1f3f78', CURRENT_TIMESTAMP),
('hat-cap-red', 'hat', 'Rote Cap', 'Klassische Quest-Cap.', 1, 'COMMON', 35, '#d63f61', '#8f263d', CURRENT_TIMESTAMP),
('hat-crown-gold', 'hat', 'Goldkrone', 'Fuer kleine Legenden.', 6, 'RARE', 35, '#f2c94c', '#9f7b18', CURRENT_TIMESTAMP),
('hat-wizard-blue', 'hat', 'Zauberhut', 'Magischer Pixelhut.', 8, 'EPIC', 35, '#3858d6', '#f2c94c', CURRENT_TIMESTAMP),
('hat-helmet-iron', 'hat', 'Ritterhelm', 'Schuetzt bei grossen Abenteuern.', 9, 'EPIC', 35, '#8ea0b8', '#445064', CURRENT_TIMESTAMP),
('top-pixel-red', 'top', 'Rotes Pixelshirt', 'Klares Abenteuer-Shirt.', 1, 'COMMON', 70, '#d63f61', '#8f263d', CURRENT_TIMESTAMP),
('top-pixel-striped', 'top', 'Streifenpulli', 'Gemusterter Pixel-Pulli.', 2, 'COMMON', 70, '#3c79d8', '#f2c94c', CURRENT_TIMESTAMP),
('top-pixel-mage', 'top', 'Magierrobe', 'Robe fuer Zauberquests.', 6, 'RARE', 72, '#7a5ccf', '#f2c94c', CURRENT_TIMESTAMP),
('top-pixel-armor', 'top', 'Pixel-Ruestung', 'Glitzernde Ruestung fuer hohe Level.', 10, 'EPIC', 72, '#8ea0b8', '#f2c94c', CURRENT_TIMESTAMP),
('bottom-pixel-skirt', 'bottom', 'Pixel-Rock', 'Beweglicher Abenteuerrock.', 1, 'COMMON', 65, '#9b5fd8', '#5f398f', CURRENT_TIMESTAMP),
('bottom-pixel-black', 'bottom', 'Schwarze Pixelhose', 'Schlichte Hose fuer alle Outfits.', 2, 'COMMON', 65, '#323846', '#171a22', CURRENT_TIMESTAMP),
('bottom-pixel-royal', 'bottom', 'Koenigshose', 'Seltene Hose mit Goldkante.', 7, 'RARE', 65, '#3858d6', '#f2c94c', CURRENT_TIMESTAMP),
('shoes-pixel-blue', 'shoes', 'Blaue Pixel-Sneaker', 'Leichte blaue Schuhe.', 1, 'COMMON', 80, '#3c79d8', '#1f3f78', CURRENT_TIMESTAMP),
('shoes-pixel-boots', 'shoes', 'Pixel-Stiefel', 'Stiefel fuer Wald und Keller.', 3, 'COMMON', 80, '#7d5635', '#4a321f', CURRENT_TIMESTAMP),
('shoes-pixel-gold', 'shoes', 'Goldschuhe', 'Glanz fuer Meisterquests.', 8, 'RARE', 80, '#f2c94c', '#9f7b18', CURRENT_TIMESTAMP),
('glasses-pixel-dark', 'glasses', 'Pixel-Sonnenbrille', 'Coole dunkle Pixelbrille.', 2, 'COMMON', 55, '#1e2533', '#ffffff', CURRENT_TIMESTAMP),
('glasses-pixel-magic', 'glasses', 'Magiebrille', 'Leuchtende Brille fuer Forscher.', 6, 'RARE', 55, '#7a5ccf', '#9ed7f2', CURRENT_TIMESTAMP),
('gadget-pixel-bag', 'gadget', 'Pixel-Tasche', 'Seitentasche fuer kleine Schaetze.', 2, 'COMMON', 90, '#d87532', '#8f4b21', CURRENT_TIMESTAMP),
('gadget-pixel-book', 'gadget', 'Zauberbuch', 'Buch voller Familienquests.', 4, 'COMMON', 90, '#7a5ccf', '#f2c94c', CURRENT_TIMESTAMP),
('gadget-pixel-potion', 'gadget', 'Trankflasche', 'Bunter Quest-Trank.', 7, 'RARE', 90, '#29b6f6', '#9b5fd8', CURRENT_TIMESTAMP),
('weapon-stick', 'weapon', 'Abenteuerstock', 'Ein stabiler Wanderstock.', 2, 'COMMON', 95, '#8b5a2b', '#4a321f', CURRENT_TIMESTAMP),
('weapon-wand', 'weapon', 'Zauberstab', 'Funkelt bei magischen Aufgaben.', 5, 'RARE', 95, '#7a5ccf', '#f2c94c', CURRENT_TIMESTAMP),
('weapon-sword', 'weapon', 'Pixel-Schwert', 'Heldenschwert fuer hohe Level.', 8, 'EPIC', 95, '#8ea0b8', '#f2c94c', CURRENT_TIMESTAMP),
('weapon-shield', 'weapon', 'Sternenschild', 'Schutzschild mit Stern.', 9, 'EPIC', 95, '#3858d6', '#f2c94c', CURRENT_TIMESTAMP),
('pet-cat', 'pet', 'Katze', 'Kleine Pixelkatze als Begleiter.', 2, 'COMMON', 100, '#f2a65a', '#4a321f', CURRENT_TIMESTAMP),
('pet-dog', 'pet', 'Hund', 'Treuer Pixelhund.', 3, 'COMMON', 100, '#b97845', '#4a321f', CURRENT_TIMESTAMP),
('pet-lion', 'pet', 'Loewe', 'Mutiger Mini-Loewe.', 6, 'RARE', 100, '#d8a13a', '#8f5b1d', CURRENT_TIMESTAMP),
('pet-tiger', 'pet', 'Tiger', 'Gestreifter Tigerfreund.', 8, 'RARE', 100, '#f28c28', '#1e2533', CURRENT_TIMESTAMP),
('pet-elephant', 'pet', 'Elefant', 'Kleiner starker Elefant.', 10, 'EPIC', 100, '#8ea0b8', '#445064', CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
