INSERT INTO "AvatarItem" ("key", "slot", "name", "description", "requiredLevel", "rarity", "layerOrder", "colorPrimary", "colorSecondary", "updatedAt") VALUES
('hair-pixel-sidepart-blond', 'hair', 'Blonder Seitenscheitel', 'Ordentlicher heller Quest-Look.', 1, 'COMMON', 30, '#e8c46a', '#9f7b18', CURRENT_TIMESTAMP),
('hair-pixel-sidepart-brown', 'hair', 'Brauner Seitenscheitel', 'Klassischer brauner Haarschnitt.', 1, 'COMMON', 30, '#6b3f25', '#3a2418', CURRENT_TIMESTAMP),
('hair-pixel-bowl-brown', 'hair', 'Pilzkopf Braun', 'Runder kurzer Pixelhaarschnitt.', 1, 'COMMON', 30, '#7a4729', '#4e2b18', CURRENT_TIMESTAMP),
('hair-pixel-pixie-black', 'hair', 'Schwarzer Pixie', 'Kurzer flotter Haarschnitt.', 2, 'COMMON', 30, '#25211f', '#111111', CURRENT_TIMESTAMP),
('hair-pixel-waves-black', 'hair', 'Schwarze Wellen', 'Dunkle weiche Haarwellen.', 2, 'COMMON', 30, '#2b2523', '#111111', CURRENT_TIMESTAMP),
('hair-pixel-waves-auburn', 'hair', 'Auburn-Wellen', 'Warme wellige Haare.', 3, 'COMMON', 30, '#a6532b', '#713316', CURRENT_TIMESTAMP),
('hair-pixel-twin-braids-blond', 'hair', 'Blonde Doppelzoepfe', 'Zwei helle Abenteuerzoepfe.', 3, 'COMMON', 30, '#f0d07a', '#b98a24', CURRENT_TIMESTAMP),
('hair-pixel-space-buns-rose', 'hair', 'Rosa Space-Buns', 'Bunte Duttknoten fuer spaetere Level.', 6, 'RARE', 30, '#d96aa8', '#8f3a68', CURRENT_TIMESTAMP),
('hair-pixel-pixie-pink', 'hair', 'Pinker Pixie', 'Frecher kurzer Fantasie-Look.', 6, 'RARE', 30, '#d96aa8', '#8f3a68', CURRENT_TIMESTAMP),
('hair-pixel-curly-purple', 'hair', 'Lila Locken', 'Magische Lockenfarbe.', 7, 'RARE', 30, '#8a5bd8', '#4c378f', CURRENT_TIMESTAMP),
('hair-pixel-twin-braids-blue', 'hair', 'Blaue Doppelzoepfe', 'Seltene blaue Abenteuerzoepfe.', 7, 'RARE', 30, '#4f7bd9', '#244b96', CURRENT_TIMESTAMP),
('hair-pixel-long-teal', 'hair', 'Tuerkises Langhaar', 'Bunter Langhaar-Look.', 8, 'RARE', 30, '#38a6a5', '#216d72', CURRENT_TIMESTAMP),
('hair-pixel-undercut-silver', 'hair', 'Silber-Undercut', 'Moderner hoher Level-Look.', 8, 'RARE', 30, '#d8dce6', '#748195', CURRENT_TIMESTAMP),
('hair-pixel-mohawk-blue', 'hair', 'Blauer Iro', 'Mutiger Heldenhaarschnitt.', 9, 'EPIC', 30, '#2f74d0', '#1d4f9f', CURRENT_TIMESTAMP),
('hair-pixel-fire-red', 'hair', 'Feuerrote Haare', 'Leuchtender Legenden-Look.', 10, 'EPIC', 30, '#d63f61', '#8f263d', CURRENT_TIMESTAMP),
('hair-pixel-comet-white', 'hair', 'Kometenweiss', 'Seltener heller Meister-Look.', 12, 'EPIC', 30, '#f1f5f9', '#94a3b8', CURRENT_TIMESTAMP),
('eyes-calm', 'eyes', 'Ruhiger Blick', 'Gelassener Blick fuer konzentrierte Quests.', 1, 'COMMON', 40, '#28384f', NULL, CURRENT_TIMESTAMP),
('eyes-round', 'eyes', 'Runde Augen', 'Offener neugieriger Blick.', 1, 'COMMON', 40, '#28384f', NULL, CURRENT_TIMESTAMP),
('eyes-curious', 'eyes', 'Neugierblick', 'Wacher Blick fuer Entdecker.', 2, 'COMMON', 40, '#2f74d0', NULL, CURRENT_TIMESTAMP),
('eyes-happy-arc', 'eyes', 'Frohe Augen', 'Sehr freundlicher Ausdruck.', 2, 'COMMON', 40, '#28384f', NULL, CURRENT_TIMESTAMP),
('eyes-determined', 'eyes', 'Entschlossener Blick', 'Fokussiert vor der naechsten Mission.', 3, 'COMMON', 40, '#243347', NULL, CURRENT_TIMESTAMP),
('eyes-magic-blue', 'eyes', 'Magieblick Blau', 'Leicht funkelnder blauer Blick.', 8, 'RARE', 40, '#29b6f6', NULL, CURRENT_TIMESTAMP),
('eyes-emerald-spark', 'eyes', 'Smaragd-Funkeln', 'Seltenes gruenes Funkeln.', 10, 'EPIC', 40, '#2f8f6f', NULL, CURRENT_TIMESTAMP),
('eyes-night', 'eyes', 'Nachtblick', 'Dunkler Legendenblick.', 12, 'EPIC', 40, '#111827', NULL, CURRENT_TIMESTAMP),
('mouth-tiny', 'mouth', 'Kleiner Mund', 'Zurueckhaltender Ausdruck.', 1, 'COMMON', 45, '#9a5a4a', NULL, CURRENT_TIMESTAMP),
('mouth-small-smile', 'mouth', 'Kleines Laecheln', 'Feines zufriedenes Laecheln.', 1, 'COMMON', 45, '#9a5a4a', NULL, CURRENT_TIMESTAMP),
('mouth-open-happy', 'mouth', 'Offen Froh', 'Frischer froehlicher Ausdruck.', 2, 'COMMON', 45, '#b85a4a', NULL, CURRENT_TIMESTAMP),
('mouth-proud', 'mouth', 'Stolz', 'Stolzer Questabschluss-Mund.', 3, 'COMMON', 45, '#8f4a3f', NULL, CURRENT_TIMESTAMP),
('mouth-silly', 'mouth', 'Quatschmund', 'Frecher lustiger Ausdruck.', 4, 'COMMON', 45, '#b85a4a', NULL, CURRENT_TIMESTAMP),
('mouth-cool', 'mouth', 'Cool', 'Laessiger Blick fuer Sammler.', 5, 'RARE', 45, '#7d4a42', NULL, CURRENT_TIMESTAMP),
('mouth-thinking', 'mouth', 'Nachdenklich', 'Ruhiger Denk-Ausdruck.', 6, 'RARE', 45, '#7d4a42', NULL, CURRENT_TIMESTAMP),
('mouth-song', 'mouth', 'Singend', 'Froher Musik-Ausdruck.', 7, 'RARE', 45, '#b85a4a', NULL, CURRENT_TIMESTAMP),
('mouth-hero', 'mouth', 'Heldenmund', 'Entschlossener hoher Level-Ausdruck.', 10, 'EPIC', 45, '#7d4a42', NULL, CURRENT_TIMESTAMP),
('mouth-legend', 'mouth', 'Legendenlaecheln', 'Seltener Meister-Ausdruck.', 14, 'EPIC', 45, '#7a5ccf', NULL, CURRENT_TIMESTAMP),
('hat-cap-red', 'hat', 'Rote Cap', 'Sportliche rote Kappe.', 1, 'COMMON', 35, '#d63f61', '#8f263d', CURRENT_TIMESTAMP),
('hat-cap-blue', 'hat', 'Blaue Cap', 'Sportliche blaue Kappe.', 2, 'COMMON', 35, '#2568d8', '#1d4f9f', CURRENT_TIMESTAMP),
('hat-cat-ears', 'hat', 'Katzenohren', 'Verspielte Pixelohren.', 3, 'COMMON', 35, '#7a4729', '#f2b28d', CURRENT_TIMESTAMP),
('hat-safari', 'hat', 'Safarihut', 'Fuer Natur- und Gartenquests.', 4, 'COMMON', 35, '#c9954a', '#7d5635', CURRENT_TIMESTAMP),
('hat-rainbow', 'hat', 'Regenbogenhut', 'Bunter Hut fuer kreative Kinder.', 5, 'RARE', 35, '#9b5fd8', '#f2c94c', CURRENT_TIMESTAMP),
('hat-pirate', 'hat', 'Piratenhut', 'Fuer Schatzsucher und Abenteuer.', 6, 'RARE', 35, '#1e2533', '#d63f61', CURRENT_TIMESTAMP),
('hat-knight', 'hat', 'Ritterhelm', 'Mutiger Helm fuer groessere Missionen.', 8, 'RARE', 35, '#8ea0b8', '#5264b8', CURRENT_TIMESTAMP),
('hat-mage-green', 'hat', 'Gruener Magierhut', 'Magischer Hut fuer hohe Level.', 9, 'RARE', 35, '#2f8f6f', '#f2c94c', CURRENT_TIMESTAMP),
('hat-crown-silver', 'hat', 'Silberkrone', 'Edle Krone fuer Sammler.', 10, 'EPIC', 35, '#d8dce6', '#748195', CURRENT_TIMESTAMP),
('hat-ninja', 'hat', 'Ninja-Kapuze', 'Leiser Legendenlook.', 11, 'EPIC', 35, '#1e2533', '#5264b8', CURRENT_TIMESTAMP),
('hat-astronaut', 'hat', 'Astronautenhelm', 'Helm fuer Weltraumquests.', 12, 'EPIC', 35, '#f1f5f9', '#29b6f6', CURRENT_TIMESTAMP),
('hat-unicorn', 'hat', 'Einhornhaube', 'Magischer Meisterhut.', 14, 'EPIC', 35, '#ffffff', '#d96aa8', CURRENT_TIMESTAMP),
('glasses-square', 'glasses', 'Eckige Brille', 'Klare eckige Brille.', 2, 'COMMON', 55, '#233044', '#ffffff', CURRENT_TIMESTAMP),
('glasses-heart', 'glasses', 'Herzbrille', 'Bunte Brille mit Herzgefuehl.', 4, 'COMMON', 55, '#d96aa8', '#ffffff', CURRENT_TIMESTAMP),
('glasses-rainbow', 'glasses', 'Regenbogenbrille', 'Seltene bunte Sammlerbrille.', 7, 'RARE', 55, '#9b5fd8', '#f2c94c', CURRENT_TIMESTAMP),
('glasses-laser', 'glasses', 'Laserbrille', 'Futuristische Meisterbrille.', 13, 'EPIC', 55, '#111827', '#29b6f6', CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
