INSERT INTO "AvatarItem" ("key", "slot", "name", "description", "requiredLevel", "rarity", "layerOrder", "colorPrimary", "colorSecondary", "updatedAt") VALUES
('hair-pixel-crop-blond', 'hair', 'Blonder Kurzschnitt', 'Heller kurzer Pixelhaarschnitt.', 1, 'COMMON', 30, '#e8c46a', '#9f7b18', CURRENT_TIMESTAMP),
('hair-pixel-crop-black', 'hair', 'Schwarzer Kurzschnitt', 'Klarer dunkler Kurzschnitt.', 1, 'COMMON', 30, '#25211f', '#111111', CURRENT_TIMESTAMP),
('hair-pixel-bob-brown', 'hair', 'Brauner Bob', 'Runder Bob im Pixelstil.', 1, 'COMMON', 30, '#7a4729', '#4e2b18', CURRENT_TIMESTAMP),
('hair-pixel-bob-red', 'hair', 'Roter Bob', 'Warmer kupferroter Bob.', 2, 'COMMON', 30, '#b45a2a', '#713316', CURRENT_TIMESTAMP),
('hair-pixel-ponytail-gold', 'hair', 'Gold-Zopf', 'Langer heller Zopf.', 2, 'COMMON', 30, '#d8a13a', '#8f5b1d', CURRENT_TIMESTAMP),
('hair-pixel-ponytail-black', 'hair', 'Nacht-Zopf', 'Dunkler langer Zopf.', 2, 'COMMON', 30, '#24262c', '#101114', CURRENT_TIMESTAMP),
('hair-pixel-curls-chestnut', 'hair', 'Kastanienlocken', 'Weiche braune Locken.', 2, 'COMMON', 30, '#8a4f2a', '#4e2b18', CURRENT_TIMESTAMP),
('hair-pixel-curls-blond', 'hair', 'Sonnenlocken', 'Helle lockige Haare.', 3, 'COMMON', 30, '#f0d07a', '#b98a24', CURRENT_TIMESTAMP),
('hair-pixel-braids-brown', 'hair', 'Braune Zoepfe', 'Zwei Abenteuerzoepfe.', 3, 'COMMON', 30, '#6b3f25', '#3a2418', CURRENT_TIMESTAMP),
('hair-pixel-braids-purple', 'hair', 'Lila Zoepfe', 'Bunte Zoepfe fuer mutige Looks.', 5, 'RARE', 30, '#8a5bd8', '#4c378f', CURRENT_TIMESTAMP),
('hair-pixel-spikes-black', 'hair', 'Stachelhaare', 'Kurze wilde Spitzen.', 3, 'COMMON', 30, '#2f2a28', '#171514', CURRENT_TIMESTAMP),
('hair-pixel-spikes-green', 'hair', 'Gruene Spitzen', 'Seltene gruene Pixelspitzen.', 6, 'RARE', 30, '#3a9f62', '#1f6b3d', CURRENT_TIMESTAMP),
('hair-pixel-long-rose', 'hair', 'Rosa Langhaar', 'Langhaar mit rosa Fantasiefarbe.', 5, 'RARE', 30, '#d96aa8', '#8f3a68', CURRENT_TIMESTAMP),
('hair-pixel-long-silver', 'hair', 'Silber-Langhaar', 'Helle silberne Pixelhaare.', 6, 'RARE', 30, '#d8dce6', '#748195', CURRENT_TIMESTAMP),
('hair-pixel-buns-gold', 'hair', 'Goldene Duttknoten', 'Zwei helle Duttknoten.', 4, 'COMMON', 30, '#e1b85c', '#9f7b18', CURRENT_TIMESTAMP),
('hair-pixel-buns-teal', 'hair', 'Tuerkise Duttknoten', 'Bunte Duttknoten fuer spaetere Level.', 7, 'RARE', 30, '#38a6a5', '#216d72', CURRENT_TIMESTAMP),
('hair-pixel-afro-dark', 'hair', 'Dunkle Wolkenlocken', 'Voluminoese dunkle Locken.', 4, 'COMMON', 30, '#2d2421', '#14100f', CURRENT_TIMESTAMP),
('hair-pixel-afro-copper', 'hair', 'Kupfer-Wolkenlocken', 'Voluminoese kupferfarbene Locken.', 5, 'RARE', 30, '#b86a32', '#713316', CURRENT_TIMESTAMP),
('eyes-blue', 'eyes', 'Blaue Augen', 'Klarer blauer Blick.', 1, 'COMMON', 40, '#2f74d0', NULL, CURRENT_TIMESTAMP),
('eyes-green', 'eyes', 'Gruene Augen', 'Frischer gruener Blick.', 1, 'COMMON', 40, '#2f8f6f', NULL, CURRENT_TIMESTAMP),
('eyes-brown', 'eyes', 'Braune Augen', 'Warmer brauner Blick.', 1, 'COMMON', 40, '#6f4a2f', NULL, CURRENT_TIMESTAMP),
('eyes-gray', 'eyes', 'Graue Augen', 'Ruhiger grauer Blick.', 1, 'COMMON', 40, '#667085', NULL, CURRENT_TIMESTAMP),
('eyes-amber', 'eyes', 'Bernsteinaugen', 'Goldener wacher Blick.', 3, 'COMMON', 40, '#c98b24', NULL, CURRENT_TIMESTAMP),
('eyes-violet', 'eyes', 'Violette Augen', 'Seltener magischer Blick.', 6, 'RARE', 40, '#7a5ccf', NULL, CURRENT_TIMESTAMP),
('eyes-wink', 'eyes', 'Zwinkerblick', 'Frecher Zwinkerblick.', 3, 'COMMON', 40, '#28384f', NULL, CURRENT_TIMESTAMP),
('eyes-sleepy', 'eyes', 'Traeumerblick', 'Ruhiger, verschlafener Blick.', 4, 'COMMON', 40, '#28384f', NULL, CURRENT_TIMESTAMP),
('eyes-star', 'eyes', 'Sternenblick', 'Leuchtender Legendenblick.', 8, 'EPIC', 40, '#d2a818', NULL, CURRENT_TIMESTAMP),
('hat-beanie-teal', 'hat', 'Tuerkise Muetze', 'Weiche Pixelmuetze.', 1, 'COMMON', 35, '#38a6a5', '#216d72', CURRENT_TIMESTAMP),
('hat-beanie-yellow', 'hat', 'Gelbe Muetze', 'Sonnige Muetze fuer draussen.', 2, 'COMMON', 35, '#f2c94c', '#9f7b18', CURRENT_TIMESTAMP),
('hat-flower-crown', 'hat', 'Blumenkranz', 'Bunter Kranz fuer Naturquests.', 4, 'COMMON', 35, '#63b66d', '#d96aa8', CURRENT_TIMESTAMP),
('hat-explorer', 'hat', 'Forscherhut', 'Hut fuer Expeditionen.', 4, 'COMMON', 35, '#c9954a', '#7d5635', CURRENT_TIMESTAMP),
('hat-headphones', 'hat', 'Pixel-Kopfhoerer', 'Musiklook fuer kreative Kinder.', 5, 'RARE', 35, '#4f5bd5', '#d96aa8', CURRENT_TIMESTAMP),
('hat-party', 'hat', 'Partyhut', 'Bunter Hut fuer besondere Tage.', 5, 'RARE', 35, '#d63f61', '#f2c94c', CURRENT_TIMESTAMP),
('hat-witch-purple', 'hat', 'Hexenhut', 'Spitzer magischer Hut.', 7, 'RARE', 35, '#7a5ccf', '#f2c94c', CURRENT_TIMESTAMP),
('hat-dragon-hood', 'hat', 'Drachenkapuze', 'Legendaere Kapuze mit Mut.', 11, 'EPIC', 35, '#2f8f6f', '#d63f61', CURRENT_TIMESTAMP),
('top-checker-red', 'top', 'Karo-Shirt', 'Rot kariertes Pixelshirt.', 2, 'COMMON', 70, '#d63f61', '#ffffff', CURRENT_TIMESTAMP),
('top-dots-teal', 'top', 'Punkte-Shirt', 'Tuerkises Shirt mit Punkten.', 2, 'COMMON', 70, '#38a6a5', '#fff3b0', CURRENT_TIMESTAMP),
('top-star-blue', 'top', 'Sternen-Shirt', 'Blaues Shirt mit Stern.', 3, 'COMMON', 70, '#2568d8', '#f2c94c', CURRENT_TIMESTAMP),
('top-rainbow', 'top', 'Regenbogenpulli', 'Bunter Pulli mit Streifen.', 4, 'COMMON', 70, '#9b5fd8', '#f2c94c', CURRENT_TIMESTAMP),
('top-overalls-denim', 'top', 'Latzhose', 'Denim-Look fuer Bastelquests.', 3, 'COMMON', 70, '#355f9f', '#f2c078', CURRENT_TIMESTAMP),
('top-hoodie-mint', 'top', 'Mint-Hoodie', 'Heller Hoodie mit Kontrastband.', 3, 'COMMON', 70, '#79c99e', '#2568d8', CURRENT_TIMESTAMP),
('top-sweater-heart', 'top', 'Herz-Pulli', 'Warmer Pulli mit Herzmotiv.', 4, 'COMMON', 70, '#d96aa8', '#ffffff', CURRENT_TIMESTAMP),
('top-jacket-space', 'top', 'Weltraumjacke', 'Dunkle Jacke mit Sternenkante.', 6, 'RARE', 72, '#25304f', '#f2c94c', CURRENT_TIMESTAMP),
('top-dress-sun', 'top', 'Sonnenkleid', 'Gelbes Pixelkleid.', 3, 'COMMON', 72, '#f2c94c', '#d87532', CURRENT_TIMESTAMP),
('top-dress-flower', 'top', 'Blumenkleid', 'Gruenes Kleid mit Blumenakzent.', 4, 'COMMON', 72, '#63b66d', '#d96aa8', CURRENT_TIMESTAMP),
('top-dress-night', 'top', 'Nachtkleid', 'Dunkles Kleid mit Sternen.', 7, 'RARE', 72, '#5264b8', '#f2c94c', CURRENT_TIMESTAMP),
('top-royal-coat', 'top', 'Koenigsmantel', 'Feiner Mantel fuer hohe Level.', 9, 'EPIC', 72, '#7a5ccf', '#f2c94c', CURRENT_TIMESTAMP),
('bottom-striped-skirt', 'bottom', 'Streifenrock', 'Rock mit klaren Streifen.', 2, 'COMMON', 65, '#d96aa8', '#ffffff', CURRENT_TIMESTAMP),
('bottom-flower-skirt', 'bottom', 'Blumenrock', 'Gruener Rock mit Blume.', 3, 'COMMON', 65, '#63b66d', '#d96aa8', CURRENT_TIMESTAMP),
('bottom-yellow-shorts', 'bottom', 'Gelbe Shorts', 'Sonnige kurze Hose.', 2, 'COMMON', 65, '#f2c94c', '#d87532', CURRENT_TIMESTAMP),
('bottom-purple-leggings', 'bottom', 'Lila Leggings', 'Bequeme Leggings.', 3, 'COMMON', 65, '#7a5ccf', '#4c378f', CURRENT_TIMESTAMP),
('bottom-checker-pants', 'bottom', 'Karo-Hose', 'Gemusterte Pixelhose.', 5, 'RARE', 65, '#323846', '#f2c94c', CURRENT_TIMESTAMP),
('bottom-rainbow-skirt', 'bottom', 'Regenbogenrock', 'Bunter Rock fuer Sammler.', 6, 'RARE', 65, '#9b5fd8', '#f2c94c', CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
